events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Cấu hình log
    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    # Cấu hình HTTP chạy qua IP trực tiếp
    server {
        listen 80;
        server_name 13.219.151.203; # Địa chỉ IP tĩnh của EC2

        # 1. Frontend Next.js
        location / {
            proxy_pass http://frontend:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # 2. Backend API
        location /api/ {
            proxy_pass http://backend:5000; # Giữ nguyên prefix /api/ khi chuyển tiếp vào backend Express
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # 3. Mock Bank (Ứng dụng Tĩnh)
        location /bank {
            alias /usr/share/nginx/html/mock-bank;
            index index.html;
        }
    }
}
